In [1]:
import numpy as np
import time

In [2]:
arr = np.array([1,2,3,4,5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [3]:
size = 100_000_000
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list time = {end-start} seconds")
np_arr = np.array(py_list)
start = time.time()
sq_array = np_arr ** 2
end = time.time()
print(f"python array time = {end-start} seconds")

python list time = 7.707083463668823 seconds
python array time = 0.41187000274658203 seconds


In [4]:
import sys

print(f"python list size= {sys.getsizeof(py_list)*len(py_list)} bytes")

print(f"numpy array size = {np_arr.nbytes} bytes")

python list size= 80000005600000000 bytes
numpy array size = 800000000 bytes


In [5]:
arr = np.array([1,2,3,4,5])
print(arr, type(arr), arr.shape)

arr2 = np.array([1,2,3,4,5,"A"])
print(arr2, type(arr2), arr2.dtype, arr2.shape)

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr2D, arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'A'] <class 'numpy.ndarray'> <U21 (6,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)


In [6]:
arr1 = np.zeros((2,3), dtype="int64")
print(arr1, arr1.shape)

arr2 = np.ones((2,3))
print(arr2, arr2.shape)

arr3 = np.full((2,3), 100)
print(arr3, arr3.shape)

arr4 = np.eye((2))
print(arr4, arr4.shape)

arr5 = np.arange(0, 11, 2)
print(arr5, arr5.shape)

arr6=np.linspace(1,100,3)
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1. 1. 1.]
 [1. 1. 1.]] (2, 3)
[[100 100 100]
 [100 100 100]] (2, 3)
[[1. 0.]
 [0. 1.]] (2, 2)
[ 0  2  4  6  8 10] (6,)
[  1.   50.5 100. ] (3,)


In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

(4, 3)
12
2
int64
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]] float64


In [8]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr, arr.shape)

reshaped = arr.reshape((2, 3))
print(reshaped, reshaped.shape)

flattened = reshaped.flatten()
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2 3]
 [4 5 6]] (2, 3)
[1 2 3 4 5 6] (6,)


In [9]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr[0][2])

3


In [10]:
arr = np.array([1,2,3,4,5,6])
idx = [0,1,3]
print(arr[idx])

[1 2 4]


In [11]:
arr = np.array([1,2,3,4,5])
print(arr[arr>2])
print(arr[arr%2==0])

[3 4 5]
[2 4]


In [12]:
arr = np.array([1,2,3,4,5])
# [start,end,step]
print(arr[1:4])
print(arr[1:])
print(arr[:4])
print(arr[::2])

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 3 5]


In [13]:
nums = [1,2,3,4,5]
sub_list = nums[1:3]
print(sub_list)
sub_list[0] = 200

print(sub_list)
print(nums)

[2, 3]
[200, 3]
[1, 2, 3, 4, 5]


In [14]:
arr = np.array([1, 2, 3, 4, 5])
sub_arr = nums[1:3].copy()
print(sub_arr)

sub_arr[0] = 200

print(sub_arr)
print(arr)

[2, 3]
[200, 3]
[1 2 3 4 5]


In [15]:
arr1 = np.array([3 + 5j])
arr2 = np.array([3 + 5j])
print(arr1+arr2)

[6.+10.j]


In [16]:
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)
print(np.sum(arr2D))
sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)
sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)
print(arr2D[0:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [17]:
arr3D = np.array([[[1, 2],[3, 4],[5, 6]], [[7, 8],[9, 10],[11, 12]]])

print(arr3D, arr3D.shape)

print(arr3D[1,1,0])

arr3D[:,0,:] = 99

print(arr3D)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
9
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [18]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
print(arr1 + arr2)
print(arr1 + 5)

[ 7  9 11 13 15]
[ 6  7  8  9 10]


In [19]:
arr = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr.shape)
print(arr2.shape)
print(arr + arr2)

(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [20]:
arr = np.array([[1,2],[3,4]])
mean = np.mean(arr)
std_dev = np.std(arr)
normalized_arr = (arr-mean)/std_dev
print(normalized_arr)
print(mean)
print(std_dev)
print(np.sqrt(5/4))

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895
1.118033988749895


In [21]:
arr = np.array([1,2,3,4,5])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))

15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0


In [22]:
arr = np.array([1,2,3,5,6,7,8,4,5])
print(np.unique(arr))

[1 2 3 4 5 6 7 8]
